# Schema for the configuration files of the OpenAI Image module.
openai_image.settings:
  type: config_object
  label: 'OpenAI Image settings'
  mapping:
    model:
      type: string
      label: 'Model'
    api_key:
      type: string
      label: 'API Key'

field.widget.settings.openai_image_openai_image_generator:
  type: mapping
  label: OpenAI Image Generator widget settings
  mapping:
    number_of_images:
      type: number
      label: 'Number of Images'
    image_size:
      type: string
      label: 'Image Size'
